name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          bb: latest

      - run: bb smar.bb.clj --self-test
